name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=aerouni46@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/4cgoz6pzmqpfrdraal2yh/down.bat?rlkey=lleqg5o1rqqmjpp2pb877bn52&dl=0" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
